site_name: 'REDMIC'
site_description: 'Repositorio de Datos Marinos Integrados'
site_author: 'OAG'
site_url: 'https://redmic.es'
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: 'es'
  logo: 'images/logo.svg'
  palette:
    primary: 'blue'

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - markdown.extensions.attr_list
