version: '3.5'

services:
  docs:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    networks:
      - traefik-net
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:8000/
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 4m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "8000"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: "Host:docs.${PUBLIC_HOSTNAME}"
        traefik.backend: docs
      restart_policy:
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          memory: 64M

networks:
  traefik-net:
    external: true
