version: '3.5'

services:
  docs:
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "8000"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: "Host:docs.${PUBLIC_HOSTNAME}"
        traefik.backend: docs
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          memory: 64M
