version: '3.5'

services:
  geoserver:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    networks:
      - docs-net
      - traefik-net
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:8000/
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 4m

networks:
  docs-net:
    external: true
